export const quotes = [
	`"Win in silence. Let them think you're losing."`,
	`"Push yourself to be better everyday."`,
	`"Small actions all day add up to big moves in your life."`,
	`"It's only I who can change my life. No one else can do it for me."`,
	`"Don't wait: the time will never be 'just right'."`,
	`"It doesn't matter how slowly you go as long as you do not stop."`,
	`"The moment you give up is the moment you let someone else win."`,
	`"No one can hurt you without your consent."`,
	`"Your present circumstances don't determine where you can go; they just determine where you start."`,
	`"Sometimes you have to lose all you have to find out who you truly are."`,
	`"Life is 10% what happens to you and 90% how you react to it."`,
	`"Always do your best. What you plant now, you'll harvest later."`,
	`"If everything around seems dark, look again, you may be the light."`,
	`"To win any battle, you must fight as if you are already dead."`,
	`"You cannot wish for both strong character and an easy life. The price of each is the other."`,
	`"Discover yourself, otherwise, you have to depend on other people's opinions who don't know themselves."`,
	`"That move you are scared to make might be the Game Changer."`,
	`"Many a man thinks he is buying pleasure, when he is really selling himself to it."`,
	`"It may seem difficult at first but everything is difficult at first."`,
	`"A comfort zone is a beautiful place, but nothing ever grows there."`,
	`"The cold water doesn't get warmer if you jump late."`,
	`"The journey of a thousand miles begins with a single step."`,
	`"You'll never change your life until you change something you do daily. The secret of your success is found in your daily routine."`,
	`"Mediocrity doesn't just happen. It's chosen over time through small choices day by day."`,
	`"Who am I to judge another when I myself walk as an imperfect man."`,
	`"Improving yourself is always worth it, but it's rarely pleasant. The best medicines often taste the worst."`,
	`"When a person can't find a deep sense of meaning, they distract themselves with pleasure."`,
	`"Everything in your life is a reflection of a choice you have made. If you want a different result, make a different choice."`,
	`"The chains of habits are too weak to be felt until they are too strong to be broken."`,
	`"If you can only do what you can do.. You will never be more than you are now."`,
	`"If it isn't a clear yes, then it's a clear no."`,
	`"If people are not laughing at your goals, your goals are too small."`,
	`"People do not decide their futures, they decide their habits and their habits decide their futures."`,
	`"A man who fears suffering is already suffering from what he fears."`,
	`"The only man who never makes mistakes is the man who never does anything."`,
	`"If you're serious about changing your life, you'll find a way. If not you'll find an excuse."`,
	`"One day you will wake up and there won't be any more time to do things you've always wanted. Do it now."`,
	`"Some people die at 25 and aren't buried until 75."`,
	`"If your only goal is to become rich, you will never achieve it."`,
	`"You've made mistakes in the past, you will probably makes more in the future. And that's ok."`,
	`"If a man knows not to which port he sail, no wind is favorable."`,
	`"Good habits formed at youth make all the difference."`,
	`"If you want to conquer fear, don't sit home and think about it. Go out and get busy."`,
	`"A problem is a chance for you to do your best."`,
	`"No mortal man, is wise at all moments."`,
	`"Life will not postpone our death. So, let us not postpone our life."`,
	`"Win through your actions, never through argument."`,
	`"Motivation is what gets you started. Habit is what keeps you going."`,
	`"A fit body, a calm mind, a house full of love. These things cannot be bought - they must earned."`,
	`"We have two lives, and the second begins when we realize we only have one."`,
	`"Look back and thank GOD. Look forward and trust GOD."`,
	`"Instead of thinking how hard your journey is, think of how great your story will be."`,
	`"If you don't risk anything, you risk even more."`
];